### PR TITLE
fix: input buttons and purse balances

### LINKED ISSUE #4: "Max" button in swap exceeds purse balance after completing a swap
Repro steps:
1. Complete a swap of two assets
2. Wait for purse balances to update
3. Click "max" button in input

Expected behavior:
The "max" button sets the input amount to the purse amount

Observed behavior:
The "max" button sets the input amount to the purse amount from before the first swap
max_incorrect

### LINKED ISSUE #7: Add 100% option for removing liquidity
100percentmissing

### LINKED ISSUE #14: Switching "to" and "from" assets before exchange rate loaded crashes app

### PR DESCRIPTION
**Pull request by samsiegart**
fixes: https://github.com/Agoric/dapp-amm/issues/7
fixes: https://github.com/Agoric/dapp-amm/issues/4
fixes: https://github.com/Agoric/dapp-amm/issues/14

In addition to the above fixes, this cleans up the redundant "setPurses" store method.

### CODE REVIEW

File: ui/src/components/components/CustomInput.jsx [hunk 1]
```diff
@@ -11,36 +11,33 @@ function CustomInput({
...
-      handleChange({ target: { value: asset[type].purse.balance } });
-  };
-  const purseBalance = useMemo(() => {
-    let obj = {};
-    let exit = 0;
+
+  const balance = useMemo(() => {
+    let purse;
+    let exit = false;
     assets.forEach(assetobj => {
```
Comment (turadg) [inline ui/src/components/components/CustomInput.jsx]: looks like you're trying to find a purse that matches some predicate. if so please use [Array.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

File: ui/src/components/components/CustomInput.jsx [hunk 2]
```diff
@@ -11,36 +11,33 @@ function CustomInput({
...
-  useEffect(() => {
-    asset[type]?.purse?.balance && !purseBalance
-      ? setBalance(asset[type]?.purse?.balance)
-      : setBalance(purseBalance);
-  }, [assets, asset[type]]);
+    return purse?.balance;
+  }, [assets, asset]);
+
+  const onMax = () => {
+    asset[type] && handleChange({ target: { value: balance } });
```
Comment (turadg) [inline ui/src/components/components/CustomInput.jsx]: I get the `&&` in JSX but let's use normal control structures in imperative code.
```suggestion
    if (asset[type]) {
      handleChange({ target: { value: balance } });
    }
```
It could also help to comment why `asset[type]` could be falsy when `onMax` is called.

**Review by turadg — CHANGES_REQUESTED** [review]
Just doing a code read, haven't checked it out or confirmed it fixes the referenced issues.

File: ui/src/components/components/CustomInput.jsx (hunk 1 above)
Comment (samsiegart) [reply ui/src/components/components/CustomInput.jsx]: Done (had to map and flatten since it's searching inside a series of nested arrays)

File: ui/src/components/components/CustomInput.jsx (hunk 2 above)
Comment (samsiegart) [reply ui/src/components/components/CustomInput.jsx]: Ack, but realized this conditional isn't needed since the max button won't render without `asset[type]`

File: ui/src/components/Swap/Swap.jsx [hunk 3]
```diff
@@ -466,10 +466,6 @@ const Swap = () => {
                   });
                   setSwapFrom(swapTo);
                   setSwapTo(swapFrom);
-                  setAssetExchange({
-                    ...assetExchange,
-                    marketRate: invertRatio(assetExchange.marketRate),
```
Comment (samsiegart) [inline ui/src/components/Swap/Swap.jsx:471]: I removed this because swapping the from/to already triggers the market rates to load again (and show a spinner) so there's no point, and it was causing a crash. I have a separate issue for showing the market rates better anyway.

File: ui/src/utils/config.js [hunk 4]
```diff
@@ -23,7 +23,6 @@ export async function refreshConfigFromWallet(walletP) {
 
   const [method, args] = dappConfig.ON_CHAIN_CONFIG;
   console.log('have method', method, 'args', args);
-  const overrideConfig = await E(walletP)[method](...args);
-  console.log('overriding with', overrideConfig);
-  dappConfig = { ...dappConfig, ...overrideConfig };
+  const chainConfig = await E(walletP)[method](...args);
+  dappConfig = { ...chainConfig, ...dappConfig };
```
Comment (samsiegart) [inline ui/src/utils/config.js:27]: This was overriding "CONTRACT_NAME" to be "VaultFactory", which we don't want

Comment (samsiegart) [reply ui/src/utils/config.js:27]: It broke the code which adds LP token purses and hence broke the add LP flow

**Review by turadg — APPROVED** [review]
