### PR TITLE
fix: various bug fixes and cleanups

### LINKED ISSUE #5: Alert strings are a bit misleading
There's a bunch of alerts that show when the dapp is first opened like "wallet connected", "please approve the dapp", "dapp connected" etc. The "wallet connected" alert shows even when ag-solo is not running which is a bit misleading.

Also, when adding liquidity, it says "liquidity pool added", but it's not creating a new pool, just adding liquidity to an existing pool.
liquidity pool added

These alerts should be fixed to be more descriptive/helpful

### LINKED ISSUE #6: "Confirm Withdrawl"
withdrawl

### PR DESCRIPTION
**Pull request by samsiegart**
fixes: https://github.com/Agoric/dapp-amm/issues/5
fixes: https://github.com/Agoric/dapp-amm/issues/6

In addition to the linked issues, this removes a lot of vestigial code since this was forked from `dapp-treasury`. None of the vaults stuff is needed. Also cleaned up some layout thrashing by removing some superfluous animations.

### CODE REVIEW

File: ui/src/components/Liquidity/Liquidity.jsx [hunk 1]
```diff
@@ -114,13 +104,12 @@ const Liquidity = () => {
...
             }}
-            transition={{ duration: 0.8 }}
-            layout
+            transition={{ duration: 0.4 }}
           >
             <div className="flex flex-col justify-between  gap-2 ">
               <h1 className="text-2xl font-semibold">Liquidity</h1>
               <h2 className="text-gray-500 ">
-                All liquidity pairs currently use {centralInfo?.petname}
+                All liquidity pairs currently use RUN.
```
Comment (turadg) [inline ui/src/components/Liquidity/Liquidity.jsx:112]: why hard code this?

File: ui/src/components/Liquidity/RemoveLiquidity/RemoveLiquidity.jsx [hunk 2]
```diff
@@ -32,7 +32,7 @@ const RemoveLiquidity = props => {
   const [currentOfferId, setCurrentOfferId] = useState(walletOffers.length);
   const [wallet, setWallet] = useState(false);
   const [removeButtonStatus, setRemoveButtonStatus] = useState(
-    'Confirm Withdrawl',
```
Comment (turadg) [inline ui/src/components/Liquidity/RemoveLiquidity/RemoveLiquidity.jsx:35]: we need a TTS that can "confirm with drawl"

**Review by turadg — APPROVED** [review]

File: ui/src/components/Liquidity/Liquidity.jsx (hunk 1 above)
Comment (samsiegart) [reply ui/src/components/Liquidity/Liquidity.jsx:112]: If it didn't load yet, it was rendering with a placeholder value that looked confusing. I figured this is not something that needs to be dynamic since everyone should understand the token as the same symbol.
